### ISSUE TITLE
Broken LumenServiceProvider

### ISSUE THREAD

**Issue by padys** [Folkloreatelier/laravel-graphql#189]
This commit (https://github.com/Folkloreatelier/laravel-graphql/commit/28d5738a3ca6ee5dfcf447503c7563586b4933fb) cuts methods from ServiceProvider required by LumenServiceProvider::boot()

**Comment by spectrumcat** [comment]
I think I have the same error:

lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Folklore\GraphQL\LumenServiceProvider::bootTypes() in lumen-graphql/vendor/folklore/graphql/src/Folklore/GraphQL/LumenServiceProvider.php:26
Stack trace:
#0 [internal function]: Folklore\GraphQL\LumenServiceProvider->boot()
#1 lumen-graphql/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#2 lumen-graphql/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#3 lumen-graphql/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#4 lumen-graphql/vendor/illuminate/container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#5 lumen-graphql/vendor/laravel/lumen-framework/src/Application.php(197): Illuminate\Container\Container->call(Array)
#6 lumen-graphql/bootstrap/app.php(84): Laravel\Lumen\Application->register(Object(Folklore\GraphQL\LumenServiceProvider))
#7 lumen-graphql/artisan(18): require('/***/***/*...')
#8 {main}

**Comment by dmongeau** [comment]
Should be fixed in 1.0.24

**Comment by spectrumcat** [comment]
New error:
```
[2017-09-06 16:00:33] lumen.ERROR: ReflectionException: Class router does not exist in lumen-graphql/vendor/illuminate/container/Container.php:752
Stack trace:
#0 lumen-graphql/vendor/illuminate/container/Container.php(752): ReflectionClass->__construct('router')
#1 lumen-graphql/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build('router')
#2 lumen-graphql/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('router', Array)
#3 lumen-graphql/vendor/laravel/lumen-framework/src/Application.php(230): Illuminate\Container\Container->make('router', Array)
#4 lumen-graphql/vendor/illuminate/container/Container.php(1195): Laravel\Lumen\Application->make('router')
#5 lumen-graphql/vendor/folklore/graphql/src/Folklore/GraphQL/ServiceProvider.php(33): Illuminate\Container\Container->offsetGet('router')
#6 lumen-graphql/vendor/folklore/graphql/src/Folklore/GraphQL/ServiceProvider.php(20): Folklore\GraphQL\ServiceProvider->bootRouter()
#7 [internal function]: Folklore\GraphQL\ServiceProvider->boot()
#8 lumen-graphql/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 lumen-graphql/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 lumen-graphql/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#11 lumen-graphql/vendor/illuminate/container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#12 lumen-graphql/vendor/laravel/lumen-framework/src/Application.php(197): Illuminate\Container\Container->call(Array)
#13 lumen-graphql/bootstrap/app.php(84): Laravel\Lumen\Application->register(Object(Folklore\GraphQL\LumenServiceProvider))
```

**Comment by dmongeau** [comment]
Sorry about that, testbench doesn't support lumen and it's hard to test. Should be fixed in 1.0.25

**Comment by padys** [comment]
Release 1.0.25 looks like it works. Thanks!

**Comment by spectrumcat** [comment]
Thank you for the fix, sadly a new error came up:

```
lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Laravel\Lumen\Application::group() in lumen-graphql/vendor/folklore/graphql/src/Folklore/GraphQL/routes.php:7
Stack trace:
#0 lumen-graphql/vendor/folklore/graphql/src/Folklore/GraphQL/LumenServiceProvider.php(39): include()
#1 lumen-graphql/vendor/folklore/graphql/src/Folklore/GraphQL/ServiceProvider.php(25): Folklore\GraphQL\LumenServiceProvider->bootRouter()
#2 [internal function]: Folklore\GraphQL\ServiceProvider->boot()
#3 lumen-graphql/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#4 lumen-graphql/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 lumen-graphql/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#6 lumen-graphql/vendor/illuminate/container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#7 lumen-graphql/vendor/laravel/lumen-framework/src/Application.php(197): Illuminate\Container\Container->call(Array)
#8 lumen-graphql/bootstrap/app.php(84): Laravel\Lumen\Application->register(Object(Folklore\GraphQL\LumenServiceProvider))
```
